# Configuração do Coolify
# Este arquivo define como o Coolify deve deployar a aplicação

build:
  dockerfile: Dockerfile

deploy:
  port: 80
  healthcheck:
    path: /health
    interval: 30s
    timeout: 3s
    retries: 3

environment:
  - SERVER_NAME=myfablab.online
  - CORS_ORIGIN=https://myfablab.online

domains:
  - myfablab.online
  - www.myfablab.online

networking:
  network: coolify