# Docker Compose para MyFabLab AI
version: '3.8'

services:
  web:
    build: .
    container_name: myfablab-web
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      - NODE_ENV=production
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      - ./logs:/var/log/nginx
      - ./backend/.env:/app/backend/.env:ro

volumes:
  logs:
    driver: local