version: '3.8'

services:
  web:
    build: .
    container_name: myfablab-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SERVER_NAME=${SERVER_NAME:-myfablab.online}
      - CORS_ORIGIN=${CORS_ORIGIN:-https://myfablab.online}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    volumes:
      # Volume para logs persistentes
      - ./logs/nginx:/var/log/nginx
    networks:
      - webnet
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

  # Container de backup (executado periodicamente)
  backup:
    image: alpine:latest
    container_name: myfablab-backup
    volumes:
      - ./backups:/backups
      - ./logs:/logs:ro
    environment:
      - BACKUP_RETENTION_DAYS=7
    command: |
      sh -c "
      apk add --no-cache tar gzip
      while true; do
        echo 'Iniciando backup...'
        TIMESTAMP=\$$(date +%Y%m%d_%H%M%S)
        tar -czf /backups/logs_\$$TIMESTAMP.tar.gz -C / logs
        
        # Remover backups antigos
        find /backups -name 'logs_*.tar.gz' -mtime +\$$BACKUP_RETENTION_DAYS -delete
        
        echo 'Backup concluído: logs_'\$$TIMESTAMP'.tar.gz'
        sleep 86400  # Executar diariamente
      done
      "
    restart: unless-stopped
    networks:
      - webnet

networks:
  webnet:
    driver: bridge