[build]
  functions = "backend"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/arena"
  to = "/index-arena.html"
  status = 200

[[redirects]]
  from = "/premium"
  to = "/index-premium.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"